<?

	$standard_model_array = array(
									array(
										"id" => "1",
										"apply" => "1",
										"code" => "ELDED",
										"name" => "Default Manual Feed Early Late",
										"description" => "Allows to calculate early late deductions from manual feed or from data feed from time module.",
										"type" => "Deduction",
										"related_to" => "Payroll",
										"remarks" => "calculations based on fixed deduction or Salary calculation",
										"view" => "-",
										"tab_in_view" => "Compensations",
									),
									/*array(
										"id" => "2",
										"apply" => "1",
										"code" => "REGO1020",
										"name" => "REGO10/20 STD PR MAN",
										"description" => "-",
										"type" => "Manual/Calculated",
										"related_to" => "Payroll",
										"remarks" => "-",
										"view" => "-",
										"tab_in_view" => "PayrollModel",
									),
									array(
										"id" => "3",
										"apply" => "1",
										"code" => "REGO50",
										"name" => "REGO50 STD PR CALC",
										"description" => "-",
										"type" => "Manual/Calculated",
										"related_to" => "Payroll",
										"remarks" => "-",
										"view" => "-",
										"tab_in_view" => "PayrollModel",
									),
									array(
										"id" => "4",
										"apply" => "1",
										"code" => "REGO100",
										"name" => "REGO100 STD PR CALC",
										"description" => "-",
										"type" => "Manual/Calculated",
										"related_to" => "Payroll",
										"remarks" => "-",
										"view" => "-",
										"tab_in_view" => "PayrollModel",
									),
									array(
										"id" => "5",
										"apply" => "1",
										"code" => "STANDARD",
										"name" => "STANDARD PR MAN",
										"description" => "-",
										"type" => "Manual/Calculated",
										"related_to" => "Payroll",
										"remarks" => "-",
										"view" => "-",
										"tab_in_view" => "PayrollModel",
									),
									array(
										"id" => "6",
										"apply" => "1",
										"code" => "PROF",
										"name" => "PROF STD PR CALC",
										"description" => "-",
										"type" => "Manual/Calculated",
										"related_to" => "Payroll",
										"remarks" => "-",
										"view" => "-",
										"tab_in_view" => "PayrollModel",
									),
									array(
										"id" => "7",
										"apply" => "1",
										"code" => "ELITE",
										"name" => "ELITE STD PR CALC",
										"description" => "-",
										"type" => "Manual/Calculated",
										"related_to" => "Payroll",
										"remarks" => "-",
										"view" => "-",
										"tab_in_view" => "PayrollModel",
									),*/
									array(
										"id" => "8",
										"apply" => "1",
										"code" => "MANUAL",
										"name" => "Manual Payroll",
										"description" => "Standard Manual Payroll Model",
										"type" => "Manual/Calculated",
										"related_to" => "Payroll",
										"remarks" => "-",
										"view" => "-",
										"tab_in_view" => "PayrollModel",
									)
								);

?>