<?php
	if(session_id()==''){session_start();}
	ob_start();
	include('../../../dbconnect/db_connect.php');
	include(DIR.'files/functions.php');
	include(DIR.'files/arrays_'.$_SESSION['rego']['lang'].'.php');
	
	$fix_allow = array();
	$fix = getFixAllowNames();
	
	$fix_deduct = array();
	$dfix = getFixDeductNames();

	$data = array();
	if(isset($_SESSION['rego']['report_id'])){
		$sql = "SELECT * FROM ".$cid."_employees WHERE emp_id = '".$_SESSION['rego']['report_id']."'";
		if($res = $dbc->query($sql)){
			if($row = $res->fetch_assoc()){
				$data = $row;
			}
			for($i=1;$i<=10;$i++){
				if($data['fix_allow_'.$i] > 0){
						$fix_allow[$fix[$i]] = $data['fix_allow_'.$i];
				}
			}
			for($i=1;$i<=5;$i++){
				if($data['fix_deduct_'.$i] > 0){
						$fix_deduct[$dfix[$i]] = $data['fix_deduct_'.$i];
				}
			}
		}
		$data['emergency_contacts'] = unserialize($data['emergency_contacts']);
		if(empty($data['emergency_contacts'][1]['name'])){$data['emergency_contacts'] = array();}
		if(empty($data['image'])){$data['image'] = 'images/profile_image.jpg';}
		if($data['calc_method'] == 'cam'){
			$calc_method = $lng['Calculate in Advance Method'];
		}else{
			$calc_method = $lng['Accumulative Calculation Method'];
		}
	}
	$total_deductions = $data['emp_tax_deductions'] + $data['tax_standard_deduction'] + $data['tax_personal_allowance'] + $data['tax_allow_pvf'] + $data['tax_allow_sso'];
	//var_dump($data['emergency_contacts']);exit;
	//var_dump($fix_allow);

$style = '
	<style>
		@page {
			margin: 10px 100px 10px 10px;
		}
		body, html, table {
			font-family: "leelawadee", "garuda";
			xfont-family: sans-serif;
			font-size: 9px;
			font-size: 13px;
		}
		.report {
			table-layout:auto;
			border-collapse:collapse;
			width:100%;
			border:0;
			margin-bottom:6px;
		}
		.report thead th {
			padding:3px 8px;
			color:#800;
			text-align:left;
			white-space:normal;
			vertical-align:middle;
			border-bottom:0.001em solid #999;
			font-weight:normal;
			background:#eee;
			font-size:14px;
		}
		.report tbody td {
			padding:3px 8px;
			color:#000;
			text-align:left;
			white-space:normal;
			vertical-align:middle;
			xborder:0.001em solid #999;
			font-weight:normal;
		}
		.report tfoot td {
			background:#ffc;
		}
		.report td.bbdot, .report th.bbdot {
			 border-bottom:1px dotted #666;
			 color:#008;
		}
		.pnr {
			font-size:10px;
			font-weight:normal;
			text-align:right;
			float:right;
			width:100px;
		}
		.green {color:green;}
		.report td.red, .report th.red {color:#900;}
		b {
			font-weight:normal;
		}
	</style>';
	
	$header = '<div>';
	if(!empty($compinfo['logofile'])){
		$header .= '<img style="height:40px;max-width:150px;float:left;margin-right:8px" src="'.ROOT.$compinfo['logofile'].'?'.time().'" />';	
	}
	$header .= '
		<div style="font-size:16px; float:left; width:60%; border:0px solid red">
			<b>'.$compinfo[$_SESSION['rego']['lang'].'_compname'].'<br>'.$lng['Employee'].' '.$_SESSION['rego']['report_id'].' '.$data[$lang.'_name'].'</b>
		</div>
		<div class="pnr" style="white-space:nowrap">
			<br>'.$lng['Page'].' {PAGENO}/{nbpg}</div><div style="clear:both"></div>
		</div>';
	
	$footer = '
		<div style="float:left;width:50%;font-size:10px;color:#999">'.
			$lng['Report generated on'].' : '.date('d/m/'.$_SESSION['rego']['year_'.$_SESSION['rego']['lang']]).'
		</div>
		<div class="pnr" style="color:#999; width:50%">'.
			$lng['Report generated by'].' : REGO HR - '.$_SESSION['rego']['name'].'</div><div style="clear:both">
		</div>';
			
	$html = '<html><body>';

	$html .= '
			<table class="report" border="0">
				<thead>
					<tr>
						<th colspan="3">
							'.$lng['Personal information'].'
						</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>'.$lng['First name'].' : '.$data['firstname'].'</td>
						<td>'.$lng['Last name'].' : '.$data['lastname'].'</td>
						<td rowspan="8" style="width:1px; padding:0; padding-top:5px"><img height="160px" src="'.ROOT.$data['image'].'" /></td>
					</tr>
					<tr>
						<td>'.$lng['Name in English'].' : '.$data['en_name'].'</td>
						<td>'.$lng['Nationality'].' : '.$data['nationality'].'</td>
					</tr>
					<tr>
						<td>'.$lng['Birthdate'].' : '.$data['birthdate'].'</td>
						<td>Age : '.getAge($data['birthdate']).'</td>
					</tr>
					<tr>
						<td>'.$lng['Gender'].' : '.$gender[$data['gender']].'</td>
						<td>'.$lng['Maritial status'].' : '.$maritial[$data['maritial']].'</td>
					</tr>
					<tr>
						<td>'.$lng['Religion'].' : '.$religion[$data['religion']].'</td>
						<td>'.$lng['Military status'].' : '.$military_status[$data['military_status']].'</td>
					</tr>
					<tr>
						<td>'.$lng['Driving license No.'].' : '.$data['drvlicense_nr'].'</td>
						<td>'.$lng['License expiry date'].' : '.$data['drvlicense_exp'].'</td>
					</tr>
					<tr>
						<td><b>'.$lng['ID card'].' :</b> '.$data['idcard_nr'].'</td>
						<td><b>'.$lng['ID card expiry date'].' :</b> '.$data['idcard_exp'].'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Place issued'].' :</b> '.$data['issued'].'</td>
						<td><b>'.$lng['Tax ID no.'].' :</b> '.$data['tax_id'].'</td>
					</tr>
				</tbody>
			</table>';
	
	$html .= '
			<table class="report" border="0" style="table-layout:fixed">
				<thead>
					<tr>
						<th colspan="3">'.$lng['Contact information'].'</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td colspan="2"><b>'.$lng['Address'].' :</b> '.$data['reg_address'].'</td>
						<td><b>'.$lng['Province'].' :</b> '.$data['province'].'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Sub district'].' :</b> '.$data['sub_district'].'</td>
						<td><b>'.$lng['District'].' :</b> '.$data['district'].'</td>
						<td><b>'.$lng['Postal code'].' :</b> '.$data['postnr'].'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Phone'].' :</b> '.$data['personal_phone'].'</td>
						<td><b>'.$lng['email'].' :</b> '.$data['personal_email'].'</td>
						<td><b>'.$lng['Country'].' :</b> '.$data['country'].'</td>
					</tr>
					<tr>
						<td colspan="3"><b>'.$lng['Current address'].' :</b> '.$data['cur_address'].'</td>
					</tr>
				</tbody>
			</table>';
	
	$html .= '
			<table class="report" border="0" style="table-layout:fixed">
				<thead>
					<tr>
						<th>'.$lng['Emergency contact information'].'</th>
					</tr>
				</thead>
				<tbody>
					<tr>';
					if(!$data['emergency_contacts']){
						$html .= '<td>'.$lng['No data available'].'</td>';
					}else{
					
					$html .= '
						<td style="padding:0">
							
							<table class="basicTable" border="0" style="width:100%; border-collapse:collapse">
								<thead>
								<tr style="">
									<th style="background:#f6f6f6; border-bottom:0">'.$lng['Name'].'</th>
									<th style="background:#f6f6f6; border-bottom:0">'.$lng['Relationship'].'</th>
									<th style="background:#f6f6f6; border-bottom:0">'.$lng['Mobile phone'].'</th>
									<th style="background:#f6f6f6; border-bottom:0">'.$lng['Work phone'].'</th>
								<tr>
								</thead>
								<tbody>';
								foreach($data['emergency_contacts'] as $k=>$v){if(!empty($v['name'])){
									$html .= '
									<tr>
										<td>'.$v['name'].'</td>
										<td>'.$v['relation'].'</td>
										<td>'.$v['mobile'].'</td>
										<td>'.$v['work'].'</td>
									</tr>';
								}}
								$html .= '
								</tbody>
							</table>
							
						</td>';
						}
					$html .= '
					</tr>
				</tbody>
			</table>';
			
	$html .= '
			<table class="report" border="0" style="">
				<thead>
					<tr>
						<th colspan="3">'.$lng['Work information'].'</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><b>'.$lng['Position'].' :</b> '.$positions[$data['position']][$lang].'</td>
						<td><b>'.$lng['Employee status'].' :</b> '.$emp_status[$data['emp_status']].'</td>
						<td><b>'.$lng['Employee type'].' :</b> '.$emp_type[$data['emp_type']].'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Joining date'].' :</b> '.date('d-m-Y', strtotime($data['joining_date'])).'</td>
						<td><b>'.$lng['Probation due date'].' :</b> '.$data['probation_date'].'</td>
						<td><b>'.$lng['Service years'].' :</b> '.getAge($data['joining_date']).'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Resign date'].' :</b> '.$data['resign_date'].'</td>
						<td colspan="2"><b>'.$lng['Employee platform'].' :</b> </td>
					</tr>
					<tr>
					</tr>
					<tr>
						<td colspan="3"><b>'.$lng['Resign reason'].' :</b> '.$data['resign_reason'].'</td>
					</tr>
				</tbody>
			</table>';
			
	$html .= '
			<table class="report" border="0" style="table-layout:fixed">
				<thead>
					<tr>
						<th colspan="3">'.$lng['Financial information'].'</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><b>'.$lng['Basic salary'].' :</b> '.number_format($data['base_salary'],2).'</td>
						<td><b>'.$lng['Day rate'].' :</b> '.$data['day_rate'].'</td>
						<td><b>'.$lng['Hour rate'].' :</b> '.$data['hour_rate'].'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Contract type'].' :</b> '.$contract_type[$data['contract_type']].'</td>
						<td><b>'.$lng['Calculation base'].' :</b> '.$calc_base[$data['calc_base']].'</td>
						<td><b>'.$lng['Base OT rate'].' :</b> <? '.$base_ot_rate[$data['base_ot_rate']].'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Calculate PVF'].' :</b> '.$noyes01[$data['calc_pvf']].'</td>
						<td><b>'.$lng['PVF rate employee'].' :</b> '.$data['pvf_rate_emp'].' %</td>
						<td><b>'.$lng['PVF rate employer'].' :</b> '.$data['pvf_rate_com'].' %</td>
					</tr>
					<tr>
						<td><b>'.$lng['Calculate PSF'].' :</b> '.$noyes01[$data['calc_pvf']].'</td>
						<td><b>'.$lng['PSF rate employee'].' :</b> '.$data['psf_rate_emp'].' %</td>
						<td><b>'.$lng['PSF rate employer'].' :</b> '.$data['psf_rate_com'].' %</td>
					</tr>
					<tr>
						<td><b>'.$lng['Calculate SSO'].' :</b> '.$noyes01[$data['calc_sso']].'</td>
						<td><b>'.$lng['Calculate Tax'].' :</b> '.$calcTax[$data['calc_tax']].'</td>
						<td><b>'.$lng['Modify Tax amount'].' :</b> '.$data['modify_tax'].'</td>
					</tr>
				</tbody>
			</table>';
			
	$html .= '<table border="0" style="width:100%">
					<tr>
						<td style="width:50%; vertical-align:top; padding-right:5px">
							<table class="report" border="0" style="table-layout:fixed">
								<thead>
									<tr>
										<th>'.$lng['Fixed allowances'].'</th>
									</tr>
								</thead>
								<tbody>';
								if($fix_allow){ foreach($fix_allow as $k=>$v){ 
									$html .= '
									<tr>
										<td><b>'.$k.' : </b>'.number_format($v,2).'</td>
									</tr>';
								}}else{
									$html .= '
									<tr>
										<td>'.$lng['No data available'].'</td>
									</tr>';
								}
					$html .= '			
								</tbody>
							</table>
						</td>
						<td style="vertical-align:top">
							<table class="report" border="0" style="table-layout:fixed">
								<thead>
									<tr>
										<th>'.$lng['Fixed deductions'].'</th>
									</tr>
								</thead>
								<tbody>';
								if($fix_deduct){ foreach($fix_deduct as $k=>$v){ 
									$html .= '
									<tr>
										<td><b>'.$k.' : </b>'.number_format($v,2).'</td>
									</tr>';
								}}else{
									$html .= '
									<tr>
										<td>'.$lng['No data available'].'</td>
									</tr>';
								}
					$html .= '			
								</tbody>
							</table>
						</td>
					</tr>
				</table>';
			
	$html .= '
			<table class="report" border="0" style="table-layout:fixed">
				<thead>
					<tr>
						<th colspan="3">'.$lng['Total tax deductions'].' : '.number_format($total_deductions,2).'</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><b>'.$lng['Standard deduction'].' :</b> '.number_format($data['tax_standard_deduction'],2).'</td>
						<td><b>'.$lng['Personal care'].' :</b> '.number_format($data['tax_personal_allowance'],2).'</td>
						<td><b>'.$lng['Spouse care'].' :</b> '.number_format($data['tax_allow_spouse'],2).'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Parents care'].' :</b> '.number_format($data['tax_allow_parents'],2).'</td>
						<td><b>'.$lng['Parents in law care'].' :</b> '.number_format($data['tax_allow_parents_inlaw'],2).'</td>
						<td><b>'.$lng['Care disabled person'].' :</b> '.number_format($data['tax_allow_disabled_person'],2).'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Child care - biological'].' :</b> '.number_format($data['tax_allow_child_bio'],2).'</td>
						<td><b>'.$lng['Child care - biological 2018/19/20'].' :</b> '.number_format($data['tax_allow_child_bio_2018'],2).'</td>
						<td><b>'.$lng['Child care - adopted'].' :</b> '.number_format($data['tax_allow_child_adopted'],2).'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Child birth (Baby bonus)'].' :</b> '.number_format($data['tax_allow_child_birth'],2).'</td>
						<td><b>'.$lng['Own health insurance'].' :</b> '.number_format($data['tax_allow_own_health'],2).'</td>
						<td><b>'.$lng['Own life insurance'].' :</b> '.number_format($data['tax_allow_own_life_insurance'],2).'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Health insurance parents'].' :</b> '.number_format($data['tax_allow_health_parents'],2).'</td>
						<td><b>'.$lng['Life insurance spouse'].' :</b> '.number_format($data['tax_allow_life_insurance_spouse'],2).'</td>
						<td><b>'.$lng['Pension fund'].' :</b> '.number_format($data['tax_allow_pension_fund'],2).'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Provident fund'].' :</b> '.number_format($data['tax_allow_pvf'],2).'</td>
						<td><b>'.$lng['NSF allowance'].' :</b> '.number_format($data['tax_allow_nsf'],2).'</td>
						<td><b>'.$lng['RMF allowance'].' :</b> '.number_format($data['tax_allow_rmf'],2).'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Social Security Fund'].' :</b> '.number_format($data['tax_allow_sso'],2).'</td>
						<td><b>'.$lng['LTF amount'].' :</b> '.number_format($data['tax_allow_ltf'],2).'</td>
						<td><b>'.$lng['Home loan interest allowance'].' :</b> '.number_format($data['tax_allow_home_loan_interest'],2).'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Donation charity'].' :</b> '.number_format($data['tax_allow_donation_charity'],2).'</td>
						<td><b>'.$lng['Donation education'].' :</b> '.number_format($data['tax_allow_donation_education'],2).'</td>
						<td><b>'.$lng['Donation flooding'].' :</b> '.number_format($data['tax_allow_donation_flood'],2).'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Exemption disabled person <65 yrs'].' :</b> '.number_format($data['tax_allow_exemp_disabled_under'],2).'</td>
						<td><b>'.$lng['Exemption tax payer => 65yrs'].' :</b> '.number_format($data['tax_allow_exemp_payer_older'],2).'</td>
						<td><b>'.$lng['First home buyers allowance'].' :</b> '.number_format($data['tax_allow_first_home'],2).'</td>
					</tr>
					<tr>
						<td><b>'.$lng['Year-end shopping allowance'].' :</b> '.number_format($data['tax_allow_year_end_shopping'],2).'</td>
						<td><b>'.$lng['Domestic tour allowance'].' :</b> '.number_format($data['tax_allow_domestic_tour'],2).'</td>
						<td><b>'.$lng['Other allowance'].' :</b> '.number_format($data['tax_allow_other'],2).'</td>
					</tr>
					<tr>
						<td colspan="3"><b>'.$lng['Tax calculation method'].' :</b> '.$calc_method.'</td>
					</tr>
				</tbody>
			</table>';
	
	$html .= '</body></html>';
		
	//echo $style.$header.$html; exit;
	
	include(DIR."mpdf7/vendor/autoload.php");
	//class mPDF ($mode, $format , $default_font_size , $default_font , $margin_left , $margin_right , $margin_top , $margin_bottom , $margin_header , $margin_footer , string $orientation ]]]]]])
	$mpdf=new mPDF('utf-8', 'A4-P', 9, '', 8, 8, 21, 12, 8, 8);
	$mpdf->SetHTMLHeader($header);
	$mpdf->SetHTMLFooter($footer);
	$mpdf->SetTitle($compinfo[$_SESSION['rego']['lang'].'_compname'].' : Employee record - '.$_SESSION['rego']['report_id'].' '.$data[$lang.'_name']);
	$mpdf->SetDisplayMode('fullpage');
	$mpdf->WriteHTML($style,1);
	$mpdf->WriteHTML($html);
	$mpdf->Output('Employee record - '.$_SESSION['rego']['report_id'].' '.$data[$lang.'_name'].'.pdf','I');
	
	exit;


?>






